version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: eslint-plugin-flowtype
    versions:
    - 5.2.1
    - 5.2.2
    - 5.3.0
    - 5.4.0
    - 5.6.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/cli"
    versions:
    - 7.13.0
    - 7.13.10
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.8
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: mongoose
    versions:
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
  - dependency-name: "@babel/node"
    versions:
    - 7.12.17
    - 7.13.0
    - 7.13.10
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.13.0
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.17
